---
title: "Notes: Exogeniety"
author: "Ivan Jacob Agaloos Pesigan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Notes: Exogeniety}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r knitr_options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  error = TRUE,
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

## Exogenous variable

- An **exogenous variable** is one whose value is determined outside the model
  and is imposed on the model.
- An **exogenous change** is a change in an exogenous variable.

## Endogenous variable

- An **endogenous variable** is a variable whose value is determined by the model.
- An **endogenous change** is a change in an endogenous variable
  in response to an exogenous change that is imposed upon the model.

## Exogeniety Assumption

- An **exogenous variable** is assumed to be fixed in repeated sampling,
  which means it is a nonstochastic variable.
- An implication of this assumption is that the error term in the econometric model is independent of the exogenous variable. 

Endogeneity can come from

- ommited variable
- measurement error
- simultaneity

\begin{equation}
  Y_i = \beta_1 + \beta_2 X_i + \varepsilon_i
\end{equation}

```{tikz, variables, echo = FALSE, fig.cap = "Exogenous and endogenous variables", fig.ext = "png", cache = TRUE}
\usetikzlibrary{er, arrows, positioning}
\begin{tikzpicture}[
  auto,
  node distance = 15mm,
  manifest/.style = {
    rectangle,
    draw,
    thick,
    inner sep = 0pt,
    minimum width = 20mm,
    minimum height = 10mm
  },
  path/.style = {
    ->,
    thick,
    >=stealth'
  },
]
  \node[manifest] (X) {Exogenous variable ($X$)};
  \node[manifest] (Y) [right = of X] {Endogenous variable ($Y$)};
  \draw [path] (X) to node {} (Y);
\end{tikzpicture}
```

\begin{equation}
  \mathbb{E}
  \left(
    \varepsilon_i
    \mid
    \mathbf{X}
  \right)
    =
    0
\end{equation}

\noindent In matrix notation,

\begin{equation}
  \mathbb{E}
  \left(
    \boldsymbol{\varepsilon}
    \mid
    \mathbf{X}
  \right)
    =
    0
\end{equation}

### Omitted Variable

In this case,
the endogeneity comes from an uncontrolled **confounding variable**,
a variable that is correlated with both the independent variable in the model and with the error term.
Equivalently,
the omitted variable affects the independent variable and separately affects the dependent variable.

### Measurement error

### Simultaneity

## References

[Wikipedia: Exogenous and Endogenous Variables](https://en.wikipedia.org/wiki/Exogenous_and_endogenous_variables)

[Wikipedia: Endogeneity (Econometrics)](https://en.wikipedia.org/wiki/Endogeneity_(econometrics))

[Wikipedia: Linear Regression - Assumptions](https://en.wikipedia.org/wiki/Linear_regression#Assumptions)

[Wikipedia: Omitted-Variable Bias](https://en.wikipedia.org/wiki/Omitted-variable_bias)
